# 01 — Data Collection

Загружаем городскую инфраструктуру из OpenStreetMap и сохраняем в `data/raw/`.

Что должно быть в ноутбуке:
- выбор города и bounding box / place name
- выбор категорий OSM (cafe, restaurant, pharmacy, bar, ...)
- загрузка через `osmnx.features_from_place`
- базовая очистка (координаты, name, category)
- сохранение в CSV / GeoJSON

In [81]:
import osmnx as ox
import pandas as pd
from pathlib import Path

RAW = Path('../data/raw')
RAW.mkdir(parents=True, exist_ok=True)

In [82]:
# TODO: choose place and categories
place = 'Yerevan, Armenia'
tags = {'amenity': ['cafe', 'restaurant', 'pharmacy', 'bar']}

gdf = ox.features_from_place(place, tags=tags)
gdf.shape
column_report = pd.DataFrame({
    'Column_Name': gdf.columns,
    'Non_Null_Count': gdf.count().values,
    'Fill_Rate_%': (gdf.count().values / len(gdf)) * 100,
    'Dtype': gdf.dtypes.values,
    'Example_Value': [gdf[col].dropna().iloc[0] for col in gdf.columns]
})

column_report = column_report.sort_values('Non_Null_Count', ascending=False)

with pd.option_context('display.max_rows', None):
    display(column_report)

for col in gdf["geometry"]:
    print(col)

,Column_Name,Non_Null_Count,Fill_Rate_%,Dtype,Example_Value
0,geometry,1613,100.000000,geometry,POINT (44.5248669 40.1783161)
5,amenity,1613,100.000000,object,restaurant
10,name,1215,75.325480,object,Օլդ Մարանի
6,check_date,933,57.842529,object,2024-11-01
11,name:en,670,41.537508,object,Old Marani
14,opening_hours,639,39.615623,object,Mo-Su 10:00-00:00
4,addr:street,602,37.321761,object,Ալեք Մանուկյանի փողոց
3,addr:housenumber,572,35.461872,object,7
7,cuisine,475,29.448233,object,georgian;armenian
1,addr:city,462,28.642281,object,Երևան
43,healthcare,455,28.208308,object,pharmacy
15,phone,432,26.782393,object,+374 10 57 33 44
18,wheelchair,431,26.720397,object,yes
13,name:ru,425,26.348419,object,Олд Марани
2,addr:country,394,24.426534,object,AM
12,name:hy,392,24.302542,object,Օլդ Մարանի
17,website,286,17.730936,object,https://www.mimino.info/
21,outdoor_seating,245,15.189089,object,yes
35,brand,234,14.507130,object,Segafredo
9,level,225,13.949163,object,0
38,brand:en,212,13.143211,object,Tashir Pizza
34,addr:postcode,207,12.833230,object,0001
36,brand:wikidata,205,12.709237,object,Q21282762
8,internet_access,186,11.531308,object,wlan
28,email,177,10.973342,object,info@samurai.com
39,brand:hy,160,9.919405,object,Տաշիր պիցցա
26,contact:instagram,159,9.857409,object,samurai_sushibar_yerevan
40,brand:ru,146,9.051457,object,Ташир Пицца
25,contact:facebook,133,8.245505,object,samuraisushiyerevan
45,payment:mastercard,131,8.121513,object,yes
46,payment:visa,129,7.997520,object,yes
29,takeaway,122,7.563546,object,yes
23,addr:region,118,7.315561,object,Երևան
22,addr:district,117,7.253565,object,Կենտրոն
136,building,113,7.005580,object,yes
30,smoking,111,6.881587,object,no
33,addr:floor,107,6.633602,object,-1
37,dispensing,82,5.083695,object,no
61,operator,80,4.959702,object,Gedeon Richter
58,payment:debit_cards,69,4.277743,object,yes
57,payment:credit_cards,66,4.091754,object,yes
68,operator:ref,65,4.029758,object,01571606
71,check_date:opening_hours,57,3.533788,object,2025-01-04
41,facebook,57,3.533788,object,https://www.facebook.com/tashirpizza/
65,payment:american_express,53,3.285803,object,yes
62,payment:cash,49,3.037818,object,yes
174,building:levels,48,2.975821,object,4
27,delivery,46,2.851829,object,yes
81,operator:en,37,2.293862,object,Gedeon Richter Pharmacy
82,operator:hy,36,2.231866,object,Գեդեոն Ռիխտեր
56,indoor_seating,36,2.231866,object,yes
59,internet_access:fee,33,2.045877,object,no
55,air_conditioning,33,2.045877,object,yes
44,drive_through,31,1.921885,object,no
86,opening_hours:signed,30,1.859888,object,no
16,toilets,28,1.735896,object,yes
75,description,28,1.735896,object,"Inside ""Tashir Mall"""
50,contact:phone,24,1.487911,object,+374 10 583119
74,shop,24,1.487911,object,wine
80,contact:telegram,22,1.363918,object,AlfaPharm
53,source,20,1.239926,object,personal survey
100,contact:website,19,1.177929,object,https://anteb.am
54,capacity,18,1.115933,object,50
90,breakfast,18,1.115933,object,"Mo-Fr 08:00-11:30; Sa-Su,PH 08:00-13:30"
89,diet:vegetarian,17,1.053937,object,yes
92,bar,16,0.991940,object,yes
93,reservation,14,0.867948,object,yes
99,addr:door,13,0.805952,object,27
97,diet:vegan,13,0.805952,object,yes
51,name:de,13,0.805952,object,Diamond Pizza
108,mobile,12,0.743955,object,+374 96 039620
103,website:menu,11,0.681959,object,https://coffeeshopcompany.am/menu/
79,contact:linkedin,11,0.681959,object,theopharma
67,payment:visa_electron,11,0.681959,object,yes
76,contact:youtube,10,0.619963,object,PizzaTashir
64,brewery,9,0.557967,object,Dargett
102,name:signed,9,0.557967,object,no
101,highchair,9,0.557967,object,no
125,contact:email,8,0.495970,object,info@mayrig.am
145,toilets:wheelchair,8,0.495970,object,no
184,type,8,0.495970,object,multipolygon
143,cocktails,7,0.433974,object,yes
73,parking,7,0.433974,object,yes
117,payment:discover_card,7,0.433974,object,yes
72,microbrewery,7,0.433974,object,no
49,note,7,0.433974,object,"Delivery service: +374 10 53 83 23, +374 10 53..."
127,toilets:unisex,6,0.371978,object,yes
85,wikidata,6,0.371978,object,Q53452662
137,internet_access:ssid,5,0.309981,object,Altar Coffeeshop
96,contact:vk,5,0.309981,object,theloftofficial
20,old_name,5,0.309981,object,Поплавок
113,fixme,5,0.309981,object,check hours
144,payment:cards,5,0.309981,object,no
48,name:fa,5,0.309981,object,کبابی های خیابان پرشیان
70,pets_allowed,5,0.309981,object,yes
47,start_date,5,0.309981,object,1963
69,dog,5,0.309981,object,yes
110,payment:mir,4,0.247985,object,yes
182,building:part,4,0.247985,object,yes
134,min_age,4,0.247985,object,18
19,alt_name,4,0.247985,object,Պապլավոկ
142,payment:visa_debit,4,0.247985,object,yes
124,addr:place,4,0.247985,object,Դավթաշենի 3-րդ թաղամաս
98,sport,4,0.247985,object,billiards
178,roof:shape,3,0.185989,object,flat
123,drink:wine,3,0.185989,object,retail
121,contact:whatsapp,3,0.185989,object,+37494743305
119,payment:contactless,3,0.185989,object,yes
132,toilets:access,3,0.185989,object,customers
149,drink:coffee,3,0.185989,object,served
63,brand:wikipedia,3,0.185989,object,"ru:36,6 (аптечная сеть)"
154,name:ja,3,0.185989,object,ザ・コーヒー
95,cash_in,3,0.185989,object,yes
167,contact:tiktok,2,0.123993,object,cofixarmenia
141,payment:jcb,2,0.123993,object,yes
88,old_name:hy,2,0.123993,object,Վերնատուն;Շուշի Պանդոկ
156,addr:street:en,2,0.123993,object,Michurin street
148,drink:beer,2,0.123993,object,served;bottled
135,instagram,2,0.123993,object,https://www.instagram.com/cj.evn/
175,layer,2,0.123993,object,1
131,diet:non-vegetarian,2,0.123993,object,yes
130,diet:meat,2,0.123993,object,yes
60,branch,2,0.123993,object,դեղատուն
128,cafe,2,0.123993,object,time-cafe
147,changing_table,2,0.123993,object,no
87,old_name:en,2,0.123993,object,tavern of the century;Shoushi Tavern;Wernatun
109,name:ar,2,0.123993,object,المدينة المائيه
32,int_name,2,0.123993,object,Little Paris
42,name:fr,2,0.123993,object,La Bohème
120,payment:maestro,2,0.123993,object,yes
118,payment:arca,2,0.123993,object,yes
91,lunch,2,0.123993,object,12:00-14:30
114,contact:tripadvisor,2,0.123993,object,g293932-d12321316
170,source:addr,1,0.061996,object,survey
169,payment:unionpay,1,0.061996,object,yes
168,disused:amenity,1,0.061996,object,cafe
24,Մելնիցա,1,0.061996,object,Շալե
166,kids_area:supervised,1,0.061996,object,no
164,kids_area:fee,1,0.061996,object,no
165,kids_area:outdoor,1,0.061996,object,no
172,diet:raw,1,0.061996,object,yes
163,check_date:diet:vegetarian,1,0.061996,object,2025-03-26
162,check_date:diet:vegan,1,0.061996,object,2025-03-26
161,bakery,1,0.061996,object,yes
171,diet:organic,1,0.061996,object,yes
126,check_date:dispensing,1,0.061996,object,2026-05-13
173,live_music,1,0.061996,object,jazz
94,ele,1,0.061996,object,-1
159,toilet,1,0.061996,object,yes
31,name:simple,1,0.061996,object,Melody
176,leisure,1,0.061996,object,playground
177,building:facade:colour,1,0.061996,object,red
179,roof:levels,1,0.061996,object,0
180,nohousenumber,1,0.061996,object,yes
181,indoor,1,0.061996,object,room
183,amenity_1,1,0.061996,object,backery
185,landuse,1,0.061996,object,retail
160,disused:shop,1,0.061996,object,yes
84,contact:foursquare,1,0.061996,object,532f1dbf498eaeabd3304377
158,diet:gluten_free,1,0.061996,object,yes
157,addr:street:ru,1,0.061996,object,улица Мичурина
122,vegetarian,1,0.061996,object,friendly
129,contact:twitter,1,0.061996,object,ttanticafe
77,fax,1,0.061996,object,+374 10 511108
133,check_date:smoking,1,0.061996,object,2024-12-06
116,phone:delivery,1,0.061996,object,+374 10 534026
115,name:ko,1,0.061996,object,소금세반송어오븐구이
112,operational_status,1,0.061996,object,closed
138,payment:cryptocurrencies,1,0.061996,object,no
139,payment:diners_club,1,0.061996,object,yes
140,payment:electronic_purses,1,0.061996,object,no
111,name:es,1,0.061996,object,Zeytuna Casa de Comida
78,official_name,1,0.061996,object,Տաշիր Պիցա Դավտթաշեն
107,pub,1,0.061996,object,yes
106,coffee,1,0.061996,object,yes
146,contact:threads,1,0.061996,object,nonocoffee_evn
105,name:it,1,0.061996,object,Pizza di Roma
104,access,1,0.061996,object,private
52,addr:housename,1,0.061996,object,Vorsord Shooting Ground
150,drink:tea,1,0.061996,object,served
151,drink:cider,1,0.061996,object,yes
152,drink:kombucha,1,0.061996,object,yes
153,was:shop,1,0.061996,object,books
83,ref,1,0.061996,object,87
155,survey:date,1,0.061996,object,2023-01-07
66,phone_1,1,0.061996,object,+374 93 25 45 48
186,was:amenity,1,0.061996,object,restaurant

POINT (44.5248669 40.1783161)
POINT (44.5244171 40.1786208)
POINT (44.5191239 40.188278)
POINT (44.5132882 40.1702504)
POINT (44.517692 40.183031)
POINT (44.5235664 40.1778934)
POINT (44.523888 40.1773437)
POINT (44.5140073 40.1889084)
POINT (44.5152042 40.187883)
POINT (44.5164919 40.1848583)
POINT (44.5179639 40.1888541)
POINT (44.5178141 40.1854041)
POINT (44.5137851 40.1853834)
POINT (44.5208333 40.1857071)
POINT (44.5107072 40.1851173)
POINT (44.5150363 40.1838787)
POINT (44.5242844 40.130388)
POINT (44.524653 40.1307286)
POINT (44.5141671 40.1761559)
POINT (44.5148069 40.181336)
POINT (44.4467752 40.1796973)
POINT (44.5164143 40.1637902)
POINT (44.4634806 40.1458151)
POINT (44.462324 40.1449749)
POINT (44.5124995 40.1633825)
POINT (44.5329208 40.1924127)
POINT (44.5510099 40.198349)
POINT (44.5191253 40.1902325)
POINT (44.4989674 40.180493)
POINT (44.4979911 40.1806243)
POINT (44.5105958 40.1553672)
POINT (44.5151704 40.1846738)
POINT (44.524557 40.1888895)
POINT (44.5178765 40.1881314)
POINT (44.5172612 40.188254)
POINT (44.4639269 40.2000357)
POINT (44.5222194 40.1775064)
POINT (44.5211786 40.1980411)
POINT (44.481506 40.1866802)
POINT (44.578695 40.2153855)
POINT (44.5138095 40.1838238)
POINT (44.5132111 40.1790635)
POINT (44.5144679 40.1820974)
POINT (44.5153396 40.1836946)
POINT (44.5460189 40.207718)
POINT (44.5490737 40.1966955)
POINT (44.4767248 40.2059402)
POINT (44.4766991 40.207477)
POINT (44.5101144 40.1794858)
POINT (44.4576285 40.1730024)
POINT (44.5428436 40.1159904)
POINT (44.5283229 40.151699)
POINT (44.5715126 40.2213988)
POINT (44.518132 40.1491157)
POINT (44.5162753 40.1492473)
POINT (44.5632885 40.1864487)
POINT (44.5650574 40.1875386)
POINT (44.5683616 40.1826584)
POINT (44.5220341 40.1414551)
POINT (44.5289727 40.2092185)
POINT (44.5026074 40.2221544)
POINT (44.4952895 40.2222303)
POINT (44.5473634 40.2256644)
POINT (44.5480442 40.2262792)
POINT (44.5048636 40.183849)
POINT (44.5134814 40.1873185)
POINT (44.5158755 40.1901511)
POINT (44.5158629 40.1900024)
POINT (44.5150773 40.1900007)
POINT (44.5273101 40.1794654)
POINT (44.5726908 40.2047429)
POINT (44.5650298 40.1709485)
POINT (44.5208629 40.2006827)
POINT (44.5200557 40.1895368)
POINT (44.5100553 40.1790388)
POINT (44.5107623 40.1790517)
POINT (44.507977 40.1772148)
POINT (44.4799983 40.204648)
POINT (44.5640031 40.1862124)
POINT (44.5104698 40.1853164)
POINT (44.5110034 40.1876549)
POINT (44.5148913 40.1801671)
POINT (44.5115861 40.185839)
POINT (44.5214236 40.1856066)
POINT (44.5173469 40.1814206)
POINT (44.5170468 40.1816477)
POINT (44.4508525 40.1743027)
POINT (44.5103413 40.1828537)
POINT (44.5237692 40.1876196)
POINT (44.5165556 40.1861706)
POINT (44.5179756 40.1883523)
POINT (44.5014939 40.1792014)
POINT (44.5142861 40.1807912)
POINT (44.4910364 40.1468852)
POINT (44.516235 40.1489669)
POINT (44.485367 40.1931136)
POINT (44.5420164 40.2299322)
POINT (44.4718647 40.1910767)
POINT (44.5183089 40.1862517)
POINT (44.5184641 40.186376)
POINT (44.5228432 40.1794807)
POINT (44.5253784 40.1851688)
POINT (44.5206345 40.1886571)
POINT (44.5136285 40.1863707)
POINT (44.5158399 40.1894704)
POINT (44.5171089 40.1893084)
POINT (44.5089368 40.1870536)
POINT (44.5181007 40.1890308)
POINT (44.5145731 40.1687523)
POINT (44.4954666 40.1522011)
POINT (44.4453078 40.1733822)
POINT (44.5013222 40.2052872)
POINT (44.4894876 40.2186133)
POINT (44.5254025 40.1864926)
POINT (44.5255514 40.1863251)
POINT (44.5134914 40.1822449)
POINT (44.5213884 40.1889564)
POINT (44.501858 40.1787722)
POINT (44.5195901 40.1868805)
POINT (44.4954471 40.1894939)
POINT (44.5059385 40.1819793)
POINT (44.5022086 40.1980872)
POINT (44.5131743 40.1998331)
POINT (44.5221098 40.1972738)
POINT (44.5535346 40.2005241)
POINT (44.5189744 40.1712071)
POINT (44.5165919 40.1813726)
POINT (44.5164586 40.1797396)
POINT (44.5205725 40.184885)
POINT (44.5112079 40.1835662)
POINT (44.5114375 40.1729676)
POINT (44.5212696 40.1806367)
POINT (44.5211882 40.1795227)
POINT (44.5208949 40.1823127)
POINT (44.5225944 40.1809313)
POINT (44.5210421 40.1796567)
POINT (44.5121619 40.1869506)
POINT (44.5176946 40.182445)
POINT (44.5159781 40.1892003)
POINT (44.5087226 40.1869336)
POINT (44.516074 40.1831761)
POINT (44.5139526 40.1736962)
POINT (44.4388293 40.1770128)
POINT (44.504509 40.1763063)
POINT (44.4435054 40.1658713)
POINT (44.5247512 40.2064239)
POINT (44.5178602 40.1847873)
POINT (44.5197488 40.1886146)
POINT (44.5087002 40.186912)
POINT (44.4801325 40.1311432)
POINT (44.5226387 40.1753211)
POINT (44.5110612 40.1854018)
POINT (44.4620787 40.1881927)
POINT (44.5107673 40.2066805)
POINT (44.5408236 40.2085675)
POINT (44.5411434 40.2095725)
POINT (44.5088402 40.1799268)
POINT (44.4883047 40.1788877)
POINT (44.5157647 40.2138896)
POINT (44.5124408 40.1858066)
POINT (44.5204384 40.1884419)
POINT (44.5157637 40.1890567)
POINT (44.5223916 40.1843045)
POINT (44.498995 40.15256)
POINT (44.5043196 40.2095505)
POINT (44.50355 40.2092167)
POINT (44.5037087 40.2085557)
POINT (44.5036608 40.2088633)
POINT (44.5146079 40.1842429)
POINT (44.5139835 40.184013)
POINT (44.463037 40.145614)
POINT (44.5084625 40.1812748)
POINT (44.5133261 40.1791568)
POINT (44.4594181 40.1835521)
POINT (44.5171879 40.2057775)
POINT (44.5230452 40.1869927)
POINT (44.4652295 40.1655231)
POINT (44.5118736 40.17183)
POINT (44.5114759 40.2071313)
POINT (44.5125515 40.1623039)
POINT (44.5365815 40.2053172)
POINT (44.5224575 40.2023957)
POINT (44.4735322 40.1940689)
POINT (44.5149975 40.1887266)
POINT (44.5039847 40.1781269)
POINT (44.5160636 40.185199)
POINT (44.5520603 40.1943327)
POINT (44.4312428 40.1914821)
POINT (44.5089137 40.1830807)
POINT (44.5356154 40.2040271)
POINT (44.5190474 40.1878024)
POINT (44.5154944 40.1805737)
POINT (44.5114742 40.1819029)
POINT (44.5170934 40.1759624)
POINT (44.5150075 40.1889053)
POINT (44.5150129 40.1889852)
POINT (44.5150217 40.1890877)
POINT (44.5157422 40.1887828)
POINT (44.5158697 40.1809925)
POINT (44.4925963 40.198153)
POINT (44.4926186 40.1982369)
POINT (44.496641 40.18979)
POINT (44.5087397 40.1815044)
POINT (44.512995 40.1817153)
POINT (44.5397159 40.2071098)
POINT (44.565529 40.2042285)
POINT (44.5195692 40.189085)
POINT (44.5064267 40.1845503)
POINT (44.5215503 40.1869456)
POINT (44.5027023 40.2038906)
POINT (44.5210563 40.1799935)
POINT (44.4934559 40.2036156)
POINT (44.490171 40.1516661)
POINT (44.4919049 40.1517984)
POINT (44.4932938 40.151614)
POINT (44.4667318 40.1627177)
POINT (44.4992264 40.2252061)
POINT (44.5168431 40.1700374)
POINT (44.4778043 40.1554117)
POINT (44.5090377 40.167469)
POINT (44.4990625 40.1526442)
POINT (44.5006786 40.1548288)
POINT (44.5154169 40.1826337)
POINT (44.5150091 40.1829955)
POINT (44.5251899 40.1783599)
POINT (44.5165942 40.1828304)
POINT (44.5127249 40.1647865)
POINT (44.5149341 40.165762)
POINT (44.5207738 40.1730105)
POINT (44.5216226 40.1748838)
POINT (44.4735129 40.1946841)
POINT (44.4462905 40.1778426)
POINT (44.4688592 40.2037916)
POINT (44.4689614 40.2034804)
POINT (44.5151827 40.1828417)
POINT (44.5141007 40.1818026)
POINT (44.512052 40.159519)
POINT (44.5157084 40.1824865)
POINT (44.4838082 40.1503639)
POINT (44.4838962 40.1503954)
POINT (44.5083817 40.18179)
POINT (44.4991916 40.2025682)
POINT (44.5033506 40.2094792)
POINT (44.5018768 40.2038439)
POINT (44.5017289 40.2047209)
POINT (44.5103695 40.174327)
POINT (44.579831 40.2165249)
POINT (44.5185601 40.1773636)
POINT (44.507587 40.1860894)
POINT (44.4873079 40.1477639)
POINT (44.5240983 40.185189)
POINT (44.4878815 40.2122093)
POINT (44.4763755 40.2051315)
POINT (44.4766887 40.2054098)
POINT (44.5137759 40.1630064)
POINT (44.5223818 40.1832472)
POINT (44.522415 40.1832589)
POINT (44.5161679 40.1822045)
POINT (44.5028189 40.1776011)
POINT (44.501152 40.2055096)
POINT (44.5008371 40.2059995)
POINT (44.5039576 40.1936533)
POINT (44.5277357 40.1910323)
POINT (44.519214 40.181415)
POINT (44.504929 40.1789129)
POINT (44.5779524 40.2174779)
POINT (44.5140988 40.1888296)
POINT (44.484313 40.1928951)
POINT (44.5159671 40.1769463)
POINT (44.559892 40.1996179)
POINT (44.512466 40.1622327)
POINT (44.5626913 40.2154366)
POINT (44.5134983 40.1793056)
POINT (44.5221261 40.1420945)
POINT (44.5116389 40.1823722)
POINT (44.5223965 40.1862391)
POINT (44.5259343 40.1856301)
POINT (44.5120001 40.1759368)
POINT (44.5230862 40.1799731)
POINT (44.4929574 40.2206215)
POINT (44.5253792 40.1865254)
POINT (44.5684256 40.1823032)
POINT (44.5132131 40.1633571)
POINT (44.5277179 40.1418353)
POINT (44.5106737 40.1558212)
POINT (44.5690028 40.1739851)
POINT (44.4844562 40.1920035)
POINT (44.5804971 40.2202636)
POINT (44.5449076 40.2061281)
POINT (44.5820851 40.2123649)
POINT (44.5269986 40.2071413)
POINT (44.5283947 40.2078411)
POINT (44.5194668 40.1813825)
POINT (44.5194997 40.180725)
POINT (44.5139233 40.1825277)
POINT (44.5144175 40.1829287)
POINT (44.5197918 40.2066707)
POINT (44.5141687 40.2069906)
POINT (44.5182081 40.1887168)
POINT (44.5181725 40.1838731)
POINT (44.5198341 40.188904)
POINT (44.565421 40.2197954)
POINT (44.5095233 40.1846546)
POINT (44.5178271 40.1788971)
POINT (44.5407967 40.2084402)
POINT (44.493303 40.1983479)
POINT (44.5050288 40.2051061)
POINT (44.5006259 40.2033234)
POINT (44.5011614 40.2034827)
POINT (44.5422391 40.2039027)
POINT (44.4911934 40.2021818)
POINT (44.4882737 40.1952355)
POINT (44.5007527 40.2061112)
POINT (44.5143316 40.1930674)
POINT (44.5727487 40.1921661)
POINT (44.518851 40.1862102)
POINT (44.585632 40.2146879)
POINT (44.5263777 40.1774061)
POINT (44.5128307 40.1864755)
POINT (44.5073975 40.2094573)
POINT (44.5159932 40.181112)
POINT (44.4873054 40.1941767)
POINT (44.5172983 40.1703686)
POINT (44.4374579 40.1720705)
POINT (44.5567879 40.2032191)
POINT (44.5476342 40.2254824)
POINT (44.438705 40.1761798)
POINT (44.522408 40.1779569)
POINT (44.4794943 40.1906042)
POINT (44.49875 40.1929708)
POINT (44.498351 40.1931391)
POINT (44.4839669 40.1927812)
POINT (44.4940595 40.2149374)
POINT (44.4995507 40.2011861)
POINT (44.4991985 40.1958906)
POINT (44.5151908 40.1837742)
POINT (44.5229584 40.2059505)
POINT (44.5205598 40.2066402)
POINT (44.5192094 40.2061818)
POINT (44.5084271 40.2071277)
POINT (44.5117164 40.1824265)
POINT (44.512071 40.1858427)
POINT (44.4635985 40.1455322)
POINT (44.5665102 40.2007491)
POINT (44.4908893 40.1931069)
POINT (44.5436691 40.2015412)
POINT (44.5154654 40.1773034)
POINT (44.5242368 40.1802095)
POINT (44.5165725 40.176513)
POINT (44.5192638 40.1763661)
POINT (44.5806618 40.2169914)
POINT (44.5760536 40.2205411)
POINT (44.5734906 40.223106)
POINT (44.5621852 40.2178818)
POINT (44.5613314 40.219064)
POINT (44.5762844 40.2196746)
POINT (44.5142603 40.1845584)
POINT (44.5329988 40.1930691)
POINT (44.528886 40.2037144)
POINT (44.5312068 40.2025211)
POINT (44.4914672 40.2200768)
POINT (44.4925651 40.1518796)
POINT (44.4923398 40.1520703)
POINT (44.5315794 40.2008667)
POINT (44.5427822 40.1659925)
POINT (44.5021371 40.2047492)
POINT (44.5095541 40.1820806)
POINT (44.4564482 40.1721999)
POINT (44.4809126 40.1490447)
POINT (44.4846465 40.1517104)
POINT (44.4806751 40.1489432)
POINT (44.5371107 40.1696084)
POINT (44.5357834 40.1696337)
POINT (44.5682575 40.1960437)
POINT (44.5093958 40.1748917)
POINT (44.4456324 40.1731388)
POINT (44.5123619 40.1786221)
POINT (44.493732 40.1894727)
POINT (44.4806267 40.2037264)
POINT (44.5159226 40.1807569)
POINT (44.5158568 40.1726014)
POINT (44.4572585 40.1737469)
POINT (44.5190004 40.1884739)
POINT (44.4680723 40.2081023)
POINT (44.524333 40.1876456)
POINT (44.5218744 40.1818598)
POINT (44.5055753 40.1766499)
POINT (44.4993321 40.1998475)
POINT (44.4974805 40.2166352)
POINT (44.5226417 40.2017792)
POINT (44.5330218 40.2257332)
POINT (44.5242044 40.1800202)
POINT (44.4512715 40.1489136)
POINT (44.5084164 40.1696478)
POINT (44.4609387 40.1833931)
POINT (44.5198611 40.2061891)
POINT (44.5649706 40.2052171)
POINT (44.4787476 40.1915632)
POINT (44.5171063 40.2043805)
POINT (44.5142846 40.1828345)
POINT (44.5162096 40.1732371)
POINT (44.5173234 40.1783416)
POINT (44.5142722 40.1892392)
POINT (44.5026239 40.2072709)
POINT (44.5787607 40.1854713)
POINT (44.5821239 40.2175741)
POINT (44.5807719 40.2170638)
POINT (44.5800021 40.2166969)
POINT (44.5478978 40.2326159)
POINT (44.5164326 40.1833386)
POINT (44.5114827 40.1857449)
POINT (44.5109907 40.1767024)
POINT (44.530858 40.1864746)
POINT (44.5121369 40.1597444)
POINT (44.5054797 40.1740067)
POINT (44.4654249 40.1911742)
POINT (44.4586174 40.1339375)
POINT (44.4686565 40.2086462)
POINT (44.4685286 40.2083817)
POINT (44.5111142 40.1783851)
POINT (44.5162544 40.1830654)
POINT (44.515109 40.1838851)
POINT (44.4607185 40.1828081)
POINT (44.4611281 40.2061297)
POINT (44.4622788 40.2068917)
POINT (44.4619467 40.2046047)
POINT (44.4621572 40.2015114)
POINT (44.5072445 40.1858139)
POINT (44.508501 40.1778668)
POINT (44.5500412 40.2188003)
POINT (44.4987484 40.1806071)
POINT (44.498937 40.1808278)
POINT (44.4993555 40.1812144)
POINT (44.4993572 40.1813863)
POINT (44.4989299 40.1825758)
POINT (44.5639033 40.1961502)
POINT (44.5641433 40.1968912)
POINT (44.5027398 40.1800288)
POINT (44.5865005 40.1889355)
POINT (44.4897264 40.2187726)
POINT (44.5277403 40.1782803)
POINT (44.4919631 40.1931506)
POINT (44.56653 40.1754173)
POINT (44.5303949 40.2051574)
POINT (44.5310789 40.204676)
POINT (44.5307945 40.2049055)
POINT (44.532617 40.1495046)
POINT (44.5240231 40.1852913)
POINT (44.5189861 40.1815038)
POINT (44.5076879 40.1838789)
POINT (44.5119407 40.1861228)
POINT (44.5143589 40.1809976)
POINT (44.5135766 40.1754209)
POINT (44.4785282 40.2053902)
POINT (44.5233052 40.1899755)
POINT (44.5150011 40.1897049)
POINT (44.5151031 40.1901647)
POINT (44.5156341 40.187947)
POINT (44.4466334 40.1803313)
POINT (44.4469428 40.1792393)
POINT (44.4461532 40.1784)
POINT (44.4459672 40.178063)
POINT (44.4893857 40.1364594)
POINT (44.4971622 40.1475796)
POINT (44.5029355 40.1802412)
POINT (44.5140562 40.2073144)
POINT (44.5122905 40.1915939)
POINT (44.5157475 40.1888506)
POINT (44.5065951 40.1790413)
POINT (44.5096233 40.1871054)
POINT (44.5225046 40.2127497)
POINT (44.5081053 40.1535068)
POINT (44.5098346 40.1872108)
POINT (44.5219918 40.1880847)
POINT (44.4459832 40.1762522)
POINT (44.4459915 40.1764185)
POINT (44.4457456 40.1720239)
POINT (44.4461923 40.1736481)
POINT (44.5341173 40.1424161)
POINT (44.5218722 40.1416915)
POINT (44.5158394 40.1770274)
POINT (44.5819483 40.2179594)
POINT (44.5822921 40.217688)
POINT (44.5169799 40.1829364)
POINT (44.5150858 40.1661461)
POINT (44.5153452 40.1805141)
POINT (44.5103454 40.1752567)
POINT (44.4881814 40.2169763)
POINT (44.5164501 40.1834538)
POINT (44.5085941 40.1868505)
POINT (44.5078365 40.206009)
POINT (44.5092116 40.1793488)
POINT (44.5041451 40.2047337)
POINT (44.4971449 40.2046982)
POINT (44.5709156 40.1992435)
POINT (44.5702525 40.1996848)
POINT (44.5174523 40.2062716)
POINT (44.517153 40.2062733)
POINT (44.5269413 40.1774109)
POINT (44.5217312 40.1828222)
POINT (44.4644339 40.1911096)
POINT (44.4907972 40.1718944)
POINT (44.4916901 40.1715319)
POINT (44.5110373 40.1815483)
POINT (44.5105595 40.2067642)
POINT (44.5231824 40.1871063)
POINT (44.5210412 40.178962)
POINT (44.5642587 40.2075349)
POINT (44.5371719 40.2031326)
POINT (44.5213965 40.2004287)
POINT (44.5110757 40.180262)
POINT (44.5868361 40.1937819)
POINT (44.5106737 40.1837567)
POINT (44.5056404 40.1915753)
POINT (44.5155052 40.1810266)
POINT (44.5123091 40.1884593)
POINT (44.5637484 40.1869657)
POINT (44.5884315 40.1910279)
POINT (44.5944307 40.1883543)
POINT (44.5148852 40.1894919)
POINT (44.5079132 40.1837492)
POINT (44.5099254 40.1749288)
POINT (44.5156144 40.1807216)
POINT (44.5169503 40.1792559)
POINT (44.5276713 40.1272478)
POINT (44.5256748 40.128587)
POINT (44.5245671 40.1314304)
POINT (44.524563 40.1322821)
POINT (44.5627779 40.1839475)
POINT (44.5629256 40.1842373)
POINT (44.4580404 40.1745172)
POINT (44.4461107 40.1726302)
POINT (44.5153566 40.176503)
POINT (44.5282956 40.1889942)
POINT (44.5163648 40.1884783)
POINT (44.5121551 40.1868562)
POINT (44.5067659 40.1825702)
POINT (44.5035112 40.1767355)
POINT (44.52081 40.2093117)
POINT (44.5197223 40.1696358)
POINT (44.4740763 40.1943862)
POINT (44.5230465 40.1891397)
POINT (44.4989718 40.2021374)
POINT (44.503105 40.2043319)
POINT (44.5226595 40.2127162)
POINT (44.5157292 40.1886017)
POINT (44.5144687 40.1817857)
POINT (44.5743982 40.2028546)
POINT (44.5171625 40.2056962)
POINT (44.5158512 40.1805383)
POINT (44.5134487 40.1888826)
POINT (44.5715629 40.2063182)
POINT (44.5130083 40.2069845)
POINT (44.5716503 40.2003861)
POINT (44.4377463 40.1684828)
POINT (44.437578 40.1687964)
POINT (44.5663002 40.1997804)
POINT (44.566758 40.2007782)
POINT (44.5133105 40.1824629)
POINT (44.5115184 40.188236)
POINT (44.5104775 40.1797163)
POINT (44.5100193 40.1758888)
POINT (44.5720122 40.1900744)
POINT (44.5047016 40.1762041)
POINT (44.5060016 40.176837)
POINT (44.5096345 40.1243337)
POINT (44.5174939 40.1581609)
POINT (44.5159709 40.1481437)
POINT (44.5159616 40.1479589)
POINT (44.5158368 40.1896975)
POINT (44.508846 40.1870037)
POINT (44.5115102 40.1777058)
POINT (44.5013205 40.1992781)
POINT (44.5069578 40.1837864)
POINT (44.5086601 40.1825687)
POINT (44.5154948 40.181506)
POINT (44.5455824 40.2080087)
POINT (44.5173041 40.1961633)
POINT (44.5076776 40.1805045)
POINT (44.5122333 40.1844877)
POINT (44.5232902 40.1878107)
POINT (44.5302737 40.1908539)
POINT (44.5096916 40.1791516)
POINT (44.4843601 40.1443373)
POINT (44.4844202 40.1447206)
POINT (44.5269872 40.1413977)
POINT (44.5644236 40.2004939)
POINT (44.49352 40.1995328)
POINT (44.5011574 40.1569043)
POINT (44.5134268 40.1661561)
POINT (44.4690576 40.2155552)
POINT (44.5209066 40.1417078)
POINT (44.544153 40.2019113)
POINT (44.5239264 40.206459)
POINT (44.5338146 40.2027873)
POINT (44.5132847 40.2070639)
POINT (44.4366892 40.1711042)
POINT (44.5738969 40.2179413)
POINT (44.4699242 40.2124713)
POINT (44.5735298 40.2238935)
POINT (44.502847 40.2020282)
POINT (44.4972584 40.2019775)
POINT (44.4992961 40.1555499)
POINT (44.5164024 40.1813318)
POINT (44.4632912 40.207814)
POINT (44.5061278 40.16278)
POINT (44.5192905 40.1417894)
POINT (44.524344 40.1767037)
POINT (44.580841 40.1887045)
POINT (44.5451551 40.2063416)
POINT (44.5159638 40.1832451)
POINT (44.5105138 40.1787247)
POINT (44.508734 40.183217)
POINT (44.5437728 40.2022153)
POINT (44.5631841 40.1956609)
POINT (44.5647714 40.19731)
POINT (44.5656404 40.1977151)
POINT (44.5604231 40.2099163)
POINT (44.5257994 40.1633966)
POINT (44.5302539 40.1411924)
POINT (44.5410803 40.1432993)
POINT (44.5246078 40.1312351)
POINT (44.475334 40.1897181)
POINT (44.4874405 40.1800701)
POINT (44.5041053 40.1783472)
POINT (44.5130439 40.175271)
POINT (44.5223019 40.1867799)
POINT (44.5910247 40.1895274)
POINT (44.5927119 40.1891381)
POINT (44.5933972 40.1886894)
POINT (44.5048988 40.2016896)
POINT (44.5094741 40.1513663)
POINT (44.5353117 40.2039542)
POINT (44.4874215 40.1800797)
POINT (44.5049366 40.2012002)
POINT (44.5223805 40.186546)
POINT (44.5674719 40.1977441)
POINT (44.4728511 40.2052578)
POINT (44.4737992 40.1963009)
POINT (44.4770591 40.2057993)
POINT (44.4767051 40.2058382)
POINT (44.4754847 40.2048365)
POINT (44.4815714 40.1943872)
POINT (44.441943 40.1660109)
POINT (44.4789657 40.1976131)
POINT (44.4858379 40.1570095)
POINT (44.4976332 40.1523024)
POINT (44.522278 40.180467)
POINT (44.4779137 40.1509076)
POINT (44.5478465 40.085646)
POINT (44.5383867 40.1764763)
POINT (44.5254533 40.1898261)
POINT (44.514824 40.1692586)
POINT (44.4435894 40.1668204)
POINT (44.4991786 40.2077548)
POINT (44.5734272 40.2229959)
POINT (44.4853275 40.2218536)
POINT (44.5956595 40.188057)
POINT (44.5340177 40.187359)
POINT (44.4933535 40.2246177)
POINT (44.5061465 40.178966)
POINT (44.5975847 40.1885638)
POINT (44.460442 40.1990462)
POINT (44.4377056 40.1747682)
POINT (44.4650331 40.1722496)
POINT (44.5331105 40.2074414)
POINT (44.5335492 40.2065313)
POINT (44.5680339 40.197894)
POINT (44.5135457 40.1822046)
POINT (44.5298789 40.1777375)
POINT (44.5129051 40.1826689)

In [83]:
cols = [c for c in ["name", "amenity", "geometry", "cuisine", "check_date", "addr:city"] if c in gdf.columns]
gdf = gdf[cols].copy()
gdf

                                                 name     amenity  \
element id
node    370052673                          Օլդ Մարանի  restaurant
        370052735                             Ֆլագման        cafe
        370055074                             Առագաստ  restaurant
        370064207                       Pizza di Roma  restaurant
        370148312                              Գուստո  restaurant
...                                               ...         ...
way     1416288209                    Sorpreso coffee        cafe
        1430212881  202 °F Alternative Coffee Brewing        cafe
        1449380224                                NaN    pharmacy
        1458860288                                NaN        cafe
        1458860289                                NaN        cafe

                                                             geometry  \
element id
node    370052673                           POINT (44.52487 40.17832)
        370052735                           POINT (44.52442 40.17862)
        370055074                           POINT (44.51912 40.18828)
        370064207                           POINT (44.51329 40.17025)
        370148312                           POINT (44.51769 40.18303)
...                                                               ...
way     1416288209  POLYGON ((44.51665 40.18804, 44.51665 40.18802...
        1430212881  POLYGON ((44.51916 40.18783, 44.51925 40.1878,...
        1449380224  POLYGON ((44.46804 40.20814, 44.46805 40.2082,...
        1458860288  POLYGON ((44.52753 40.18165, 44.52755 40.18165...
        1458860289  POLYGON ((44.52753 40.1817, 44.52755 40.1817, ...

                              cuisine  check_date addr:city
element id
node    370052673   georgian;armenian  2024-11-01     Երևան
        370052735                 NaN  2023-05-28       NaN
        370055074                 NaN  2023-09-03       NaN
        370064207               pizza  2022-05-19     Երևան
        370148312             italian         NaN       NaN
...                               ...         ...       ...
way     1416288209        coffee_shop  2025-03-16       NaN
        1430212881        coffee_shop  2023-09-10       NaN
        1449380224                NaN         NaN       NaN
        1458860288        coffee_shop         NaN       NaN
        1458860289        coffee_shop         NaN       NaN

[1613 rows x 6 columns]