# 01 — Data Collection

Загружаем городскую инфраструктуру из OpenStreetMap и сохраняем в `data/raw/`.

Что должно быть в ноутбуке:
- выбор города и bounding box / place name
- выбор категорий OSM (cafe, restaurant, pharmacy, bar, ...)
- загрузка через `osmnx.features_from_place`
- базовая очистка (координаты, name, category)
- сохранение в CSV / GeoJSON

In [305]:
import osmnx as ox
import pandas as pd
from pathlib import Path

def show_all_columns(q):
    column_report = pd.DataFrame({
        'Column_Name': q.columns,
        'Non_Null_Count': q.count().values,
        'Fill_Rate_%': (q.count().values / len(q)) * 100,
        'Dtype': q.dtypes.values,
        'Example_Value': [q[col].dropna().iloc[0] if not q[col].dropna().empty else "---" for col in q.columns]
    })
    column_report = column_report.sort_values('Non_Null_Count', ascending=False)
    with pd.option_context('display.max_rows', None):
        display(column_report)

RAW = Path('../data/raw')
RAW.mkdir(parents=True, exist_ok=True)

In [306]:
# TODO: choose place and categories
place = 'Armenia'
tags = {'amenity': ['cafe', 'restaurant', 'pharmacy', 'bar']}
q = ox.features_from_place(place, tags=tags)
q.shape

show_all_columns(gdf)

/opt/anaconda3/lib/python3.13/site-packages/osmnx/_overpass.py:271: UserWarning: This area is 16 times your configured Overpass max query area size. It will automatically be divided up into multiple sub-queries accordingly. This may take a long time.
  multi_poly_proj = utils_geo._consolidate_subdivide_geometry(poly_proj)

,Column_Name,Non_Null_Count,Fill_Rate_%,Dtype,Example_Value
0,geometry,2782,100.000000,geometry,POINT (44.5248669 40.1783161)
1,amenity,2782,100.000000,object,restaurant
232,lat,2782,100.000000,float64,40.178316
233,lon,2782,100.000000,float64,44.524867
2,name,1950,70.093458,object,Օլդ Մարանի
3,name:en,1093,39.288282,object,Old Marani
29,check_date,1070,38.461538,object,2024-11-01
19,opening_hours,861,30.948958,object,Mo-Su 10:00-00:00
27,addr:street,857,30.805176,object,Ալեք Մանուկյանի փողոց
24,addr:housenumber,749,26.923077,object,7
4,name:ru,698,25.089863,object,Олд Марани
5,addr:city,689,24.766355,object,Երևան
17,cuisine,683,24.550683,object,georgian;armenian
13,healthcare,649,23.328541,object,pharmacy
22,phone,608,21.854781,object,+374 10 57 33 44
14,name:hy,595,21.387491,object,Օլդ Մարանի
6,addr:country,527,18.943206,object,AM
16,wheelchair,465,16.714594,object,yes
26,website,340,12.221423,object,https://www.mimino.info/
107,building,336,12.077642,object,yes
21,outdoor_seating,325,11.682243,object,yes
18,internet_access,292,10.496046,object,wlan
8,brand,291,10.460101,object,Segafredo
34,addr:postcode,265,9.525521,object,0001
9,brand:en,265,9.525521,object,Tashir Pizza
12,brand:wikidata,257,9.237958,object,Q21282762
43,level,237,8.519051,object,0
25,email,220,7.907980,object,info@samurai.com
45,contact:instagram,218,7.836089,object,samurai_sushibar_yerevan
10,brand:hy,208,7.476636,object,Տաշիր պիցցա
50,contact:facebook,194,6.973400,object,samuraisushiyerevan
11,brand:ru,191,6.865564,object,Ташир Пицца
28,takeaway,156,5.607477,object,yes
7,addr:region,146,5.248023,object,Երևան
31,smoking,138,4.960460,object,no
46,payment:mastercard,137,4.924515,object,yes
47,payment:visa,135,4.852624,object,yes
44,addr:district,117,4.205607,object,Կենտրոն
38,dispensing,116,4.169662,object,no
111,addr:floor,110,3.953990,object,-1
15,operator,107,3.846154,object,caucasian
200,building:levels,85,3.055356,object,4
62,payment:debit_cards,75,2.695902,object,no
61,payment:credit_cards,72,2.588066,object,no
91,contact:phone,70,2.516175,object,+374 10 583119
70,facebook,69,2.480230,object,https://www.facebook.com/tashirpizza/
81,operator:ref,65,2.336449,object,01571606
66,delivery,59,2.120776,object,yes
82,check_date:opening_hours,57,2.048886,object,2025-01-04
60,indoor_seating,57,2.048886,object,yes
77,payment:american_express,54,1.941050,object,yes
88,payment:cash,49,1.761323,object,yes
36,internet_access:fee,46,1.653487,object,no
55,air_conditioning,42,1.509705,object,no
56,contact:website,40,1.437815,object,https://anteb.am
37,description,39,1.401869,object,Outdoor seating only. Hookah.
93,contact:email,38,1.365924,object,red-fort@mail.ru
79,operator:en,37,1.329978,object,Gedeon Richter Pharmacy
52,drive_through,36,1.294033,object,no
80,operator:hy,36,1.294033,object,Գեդեոն Ռիխտեր
78,toilets,32,1.150252,object,yes
83,opening_hours:signed,30,1.078361,object,no
53,image,28,1.006470,object,http://akunkidrakht.am/wp-content/uploads/2020/07/ad_paradise_area_13.jpg
30,capacity,28,1.006470,object,80
59,diet:vegetarian,28,1.006470,object,yes
42,shop,27,0.970525,object,wine
108,contact:telegram,26,0.934579,object,AlfaPharm
104,source,23,0.826743,object,personal survey
58,diet:vegan,19,0.682962,object,yes
136,breakfast,18,0.647017,object,"Mo-Fr 08:00-11:30; Sa-Su,PH 08:00-13:30"
67,reservation,18,0.647017,object,recommended
113,bar,17,0.611071,object,no
23,tourism,16,0.575126,object,hotel
103,contact:tripadvisor,15,0.539180,object,g293932-d12321316
106,website:menu,15,0.539180,object,https://coffeeshopcompany.am/menu/
135,addr:door,14,0.503235,object,48A
121,name:de,13,0.467290,object,Diamond Pizza
73,mobile,13,0.467290,object,+374 96 039620
102,payment:visa_electron,12,0.431344,object,yes
75,contact:linkedin,11,0.395399,object,theopharma
33,fixme,11,0.395399,object,probably closed (Sep2024)
84,start_date,11,0.395399,object,1963
85,contact:youtube,11,0.395399,object,PizzaTashir
89,name:signed,10,0.359454,object,no
40,note,9,0.323508,object,"Delivery service: +374 10 53 83 23, +374 10 53 03 21"
123,brewery,9,0.323508,object,Dargett
140,highchair,9,0.323508,object,no
164,toilets:wheelchair,9,0.323508,object,no
213,contact:booking,8,0.287563,object,https://www.booking.com/hotel/am/ani-forest-hills-and-resort-dilijan
212,roof:levels,8,0.287563,object,1
230,type,8,0.287563,object,multipolygon
116,old_name,7,0.251618,object,Поплавок
114,payment:cards,7,0.251618,object,no
126,microbrewery,7,0.251618,object,no
148,payment:discover_card,7,0.251618,object,yes
127,parking,7,0.251618,object,yes
163,cocktails,7,0.251618,object,yes
54,alt_name,7,0.251618,object,Պապլավոկ
64,int_name,7,0.251618,object,Little Paris
112,attribution,6,0.215672,object,Տիգրան Սարգսյան
194,socket:schuko,6,0.215672,object,6
132,wikidata,6,0.215672,object,Q53452662
155,toilets:unisex,6,0.215672,object,yes
124,dog,5,0.179727,object,yes
214,leisure,5,0.179727,object,resort
193,power_supply,5,0.179727,object,yes
202,roof:shape,5,0.179727,object,flat
162,internet_access:ssid,5,0.179727,object,Altar Coffeeshop
101,payment:visa_debit,5,0.179727,object,yes
139,contact:vk,5,0.179727,object,theloftofficial
120,name:fa,5,0.179727,object,کبابی های خیابان پرشیان
125,pets_allowed,5,0.179727,object,yes
168,drink:coffee,5,0.179727,object,served
105,drink:wine,5,0.179727,object,retail
199,barrier,4,0.143781,object,wall
204,building:part,4,0.143781,object,yes
76,cash_in,4,0.143781,object,yes
90,sport,4,0.143781,object,billiards
160,min_age,4,0.143781,object,18
144,payment:mir,4,0.143781,object,yes
153,addr:place,4,0.143781,object,Դավթաշենի 3-րդ թաղամաս
173,name:ja,3,0.107836,object,ザ・コーヒー
150,payment:contactless,3,0.107836,object,yes
134,old_name:hy,3,0.107836,object,Վերնատուն;Շուշի Պանդոկ
167,drink:beer,3,0.107836,object,served;bottled
195,price,3,0.107836,object,budget
133,old_name:en,3,0.107836,object,tavern of the century;Shoushi Tavern;Wernatun
151,contact:whatsapp,3,0.107836,object,+37494743305
119,name:fr,3,0.107836,object,La Bohème
65,brand:wikipedia,3,0.107836,object,"ru:36,6 (аптечная сеть)"
98,payment:jcb,3,0.107836,object,yes
115,toilets:access,3,0.107836,object,customers
99,payment:maestro,3,0.107836,object,yes
86,diet:non-vegetarian,3,0.107836,object,yes
181,check_date:diet:vegan,2,0.071891,object,2025-03-26
72,name:ar,2,0.071891,object,المدينة المائيه
158,diet:meat,2,0.071891,object,yes
159,check_date:smoking,2,0.071891,object,2024-12-06
161,instagram,2,0.071891,object,https://www.instagram.com/cj.evn/
87,diet:organic,2,0.071891,object,yes
166,changing_table,2,0.071891,object,no
210,visual:condition,2,0.071891,object,fair
95,payment:cryptocurrencies,2,0.071891,object,no
209,roof:material,2,0.071891,object,metal sheet
207,building:material,2,0.071891,object,concrete
175,addr:street:en,2,0.071891,object,Michurin street
203,landuse,2,0.071891,object,retail
180,bakery,2,0.071891,object,yes
57,diet:halal,2,0.071891,object,yes
186,contact:tiktok,2,0.071891,object,cofixarmenia
156,cafe,2,0.071891,object,time-cafe
92,value,2,0.071891,object,website:menu=https://i.imgur.com/SetaaDr.jpg
137,lunch,2,0.071891,object,12:00-14:30
20,wifi,2,0.071891,object,"Theoretically there is wifi, but weak or useless signal"
96,payment:diners_club,2,0.071891,object,yes
97,payment:electronic_purses,2,0.071891,object,no
149,payment:arca,2,0.071891,object,yes
122,branch,2,0.071891,object,դեղատուն
224,layer,2,0.071891,object,1
49,internet_access:type,1,0.035945,object,WiFi
206,building:form,1,0.035945,object,rectangular
205,amenity_1,1,0.035945,object,backery
48,highway,1,0.035945,object,rest_area
229,building:levels:underground,1,0.035945,object,1
32,name:el,1,0.035945,object,Εστιατόριο
219,building:colour,1,0.035945,object,red
201,diet:local,1,0.035945,object,yes
228,indoor,1,0.035945,object,room
198,wikipedia,1,0.035945,object,en:Raketa (hydrofoil)
231,was:amenity,1,0.035945,object,restaurant
197,historic,1,0.035945,object,ship
196,name:zh,1,0.035945,object,藥店
63,addr:housename,1,0.035945,object,Vorsord Shooting Ground
51,atm,1,0.035945,object,no
227,nohousenumber,1,0.035945,object,yes
208,landscape,1,0.035945,object,mountain
222,building:max_level,1,0.035945,object,2
218,check_date:diet:halal,1,0.035945,object,2026-03-01
217,power,1,0.035945,object,outlet
216,source:addr:housenumber,1,0.035945,object,streetside
220,disused,1,0.035945,object,yes
192,phone2,1,0.035945,object,099 01 15 20
221,building:condition,1,0.035945,object,good
223,height,1,0.035945,object,5
226,stars,1,0.035945,object,5
215,rooms,1,0.035945,object,102
35,information,1,0.035945,object,office
225,building:facade:colour,1,0.035945,object,red
39,food,1,0.035945,object,yes
41,access,1,0.035945,object,private
211,old_name:ru,1,0.035945,object,Скотобойня
68,description:ru,1,0.035945,object,Ресторан на обрыве
129,official_name,1,0.035945,object,Տաշիր Պիցա Դավտթաշեն
191,live_music,1,0.035945,object,jazz
165,contact:threads,1,0.035945,object,nonocoffee_evn
157,contact:twitter,1,0.035945,object,ttanticafe
94,payment:coins,1,0.035945,object,yes
154,check_date:dispensing,1,0.035945,object,2026-05-13
152,vegetarian,1,0.035945,object,friendly
147,phone:delivery,1,0.035945,object,+374 10 534026
146,name:ko,1,0.035945,object,소금세반송어오븐구이
145,name:es,1,0.035945,object,Zeytuna Casa de Comida
143,pub,1,0.035945,object,yes
142,coffee,1,0.035945,object,yes
141,name:it,1,0.035945,object,Pizza di Roma
100,payment:notes,1,0.035945,object,yes
109,addr:province:ar,1,0.035945,object,Լոռի
138,ele,1,0.035945,object,-1
110,addr:province:en,1,0.035945,object,Lori
118,name:simple,1,0.035945,object,Melody
128,fax,1,0.035945,object,+374 10 511108
131,contact:foursquare,1,0.035945,object,532f1dbf498eaeabd3304377
74,operational_status,1,0.035945,object,closed
71,name_1,1,0.035945,object,at Goqor fish restaurant
190,diet:raw,1,0.035945,object,yes
169,drink:tea,1,0.035945,object,served
189,source:addr,1,0.035945,object,survey
188,payment:unionpay,1,0.035945,object,yes
187,disused:amenity,1,0.035945,object,cafe
185,kids_area:supervised,1,0.035945,object,no
184,kids_area:outdoor,1,0.035945,object,no
183,kids_area:fee,1,0.035945,object,no
182,check_date:diet:vegetarian,1,0.035945,object,2025-03-26
130,ref,1,0.035945,object,87
179,disused:shop,1,0.035945,object,yes
178,toilet,1,0.035945,object,yes
177,diet:gluten_free,1,0.035945,object,yes
176,addr:street:ru,1,0.035945,object,улица Мичурина
174,survey:date,1,0.035945,object,2023-01-07
69,phone_1,1,0.035945,object,+374 93 25 45 48
172,was:shop,1,0.035945,object,books
171,drink:kombucha,1,0.035945,object,yes
170,drink:cider,1,0.035945,object,yes
117,Մելնիցա,1,0.035945,object,Շալե

In [307]:
centroids = gdf.geometry.centroid

/var/folders/62/v111z_vs2tg87mfz2gzmwr4r0000gn/T/ipykernel_34591/3439640891.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  centroids = gdf.geometry.centroid

In [308]:
gdf['lat'] = centroids.y
gdf['lon'] = centroids.x

In [ ]:
no_name_gdf = gdf[gdf['name'].isna()]
# есть 100 заведений с name:en и без name
no_name_en_gdf = no_name_gdf[no_name_gdf['name:en'].isna()]
# есть 23 заведения с name:ru и без name:en
no_name_ru_gdf = no_name_en_gdf[no_name_en_gdf['name:ru'].isna()]
no_name_signed_gdf = no_name_ru_gdf[no_name_ru_gdf['name:signed'].isna()]
no_name_hy_gdf = no_name_signed_gdf[no_name_signed_gdf['name:hy'].isna()]
show_all_columns(no_name_hy_gdf)

,Column_Name,Non_Null_Count,Fill_Rate_%,Dtype,Example_Value
0,geometry,697,100.000000,geometry,POINT (44.524653 40.1307286)
1,amenity,697,100.000000,object,pharmacy
232,lat,697,100.000000,float64,40.130729
233,lon,697,100.000000,float64,44.524653
13,healthcare,291,41.750359,object,pharmacy
29,check_date,203,29.124821,object,2026-03-16
107,building,89,12.769010,object,yes
27,addr:street,86,12.338594,object,Տիտոգրադյան փողոց
16,wheelchair,82,11.764706,object,limited
19,opening_hours,80,11.477762,object,Mo-Fr 08:30-23:00
24,addr:housenumber,67,9.612626,object,47
5,addr:city,53,7.604017,object,Երևան
38,dispensing,51,7.317073,object,no
17,cuisine,47,6.743185,object,kebab
6,addr:country,41,5.882353,object,AM
43,level,34,4.878049,object,0
22,phone,31,4.447633,object,+374 10 303030
8,brand,22,3.156385,object,ՀայՓոստ.Մեդ
50,contact:facebook,20,2.869440,object,gedeon.richter.pharmacy
26,website,20,2.869440,object,https://www.haypost.am/am/HayPost-Med
9,brand:en,20,2.869440,object,HayPost.Med
21,outdoor_seating,18,2.582496,object,no
45,contact:instagram,17,2.439024,object,gedeon.richter.pharmacy
25,email,16,2.295552,object,online@rg-pharm.am
111,addr:floor,16,2.295552,object,1
10,brand:hy,15,2.152080,object,ՀայՓոստ.Մեդ
15,operator,14,2.008608,object,Армен
28,takeaway,14,2.008608,object,only
200,building:levels,12,1.721664,object,2
81,operator:ref,12,1.721664,object,01200273
47,payment:visa,10,1.434720,object,yes
46,payment:mastercard,10,1.434720,object,yes
11,brand:ru,9,1.291248,object,Гедеон Рихтер
34,addr:postcode,9,1.291248,object,0069
18,internet_access,8,1.147776,object,no
80,operator:hy,7,1.004304,object,Կամելիա
79,operator:en,7,1.004304,object,Kamelia
52,drive_through,6,0.860832,object,no
37,description,5,0.717360,object,"You can camp here for 2€ if it's bad weather, since it has some shelters agains the rain."
104,source,5,0.717360,object,survey
75,contact:linkedin,5,0.717360,object,theopharma
88,payment:cash,5,0.717360,object,yes
108,contact:telegram,5,0.717360,object,AlfaPharm
7,addr:region,5,0.717360,object,Երևան
60,indoor_seating,4,0.573888,object,yes
44,addr:district,4,0.573888,object,Մալաթիա-Սեբաստիա
40,note,4,0.573888,object,14-FEB-12 15:31:43
33,fixme,3,0.430416,object,location
31,smoking,3,0.430416,object,yes
78,toilets,3,0.430416,object,yes
73,mobile,3,0.430416,object,+374 96 119620
62,payment:debit_cards,3,0.430416,object,yes
30,capacity,2,0.286944,object,20
66,delivery,2,0.286944,object,yes
130,ref,1,0.143472,object,87
20,wifi,1,0.143472,object,"Theoretically there is wifi, but weak or useless signal"
174,survey:date,1,0.143472,object,2023-01-07
82,check_date:opening_hours,1,0.143472,object,2024-09-29
83,opening_hours:signed,1,0.143472,object,no
85,contact:youtube,1,0.143472,object,tonusles5273
175,addr:street:en,1,0.143472,object,Zoravar Andranik street
184,kids_area:outdoor,1,0.143472,object,no
178,toilet,1,0.143472,object,yes
180,bakery,1,0.143472,object,yes
183,kids_area:fee,1,0.143472,object,no
185,kids_area:supervised,1,0.143472,object,no
99,payment:maestro,1,0.143472,object,yes
12,brand:wikidata,1,0.143472,object,Q118727363
101,payment:visa_debit,1,0.143472,object,yes
102,payment:visa_electron,1,0.143472,object,yes
189,source:addr,1,0.143472,object,survey
114,payment:cards,1,0.143472,object,no
36,internet_access:fee,1,0.143472,object,customers
74,operational_status,1,0.143472,object,closed
135,addr:door,1,0.143472,object,45
61,payment:credit_cards,1,0.143472,object,no
164,toilets:wheelchair,1,0.143472,object,no
136,breakfast,1,0.143472,object,08:00-24:00
53,image,1,0.143472,object,https://i.imgur.com/wdOl8u3.jpg
51,atm,1,0.143472,object,no
113,bar,1,0.143472,object,yes
220,disused,1,0.143472,object,yes
67,reservation,1,0.143472,object,no
150,payment:contactless,1,0.143472,object,yes
42,shop,1,0.143472,object,bakery
41,access,1,0.143472,object,private
149,payment:arca,1,0.143472,object,yes
55,air_conditioning,1,0.143472,object,no
188,payment:unionpay,0,0.000000,object,---
160,min_age,0,0.000000,object,---
187,disused:amenity,0,0.000000,object,---
163,cocktails,0,0.000000,object,---
161,instagram,0,0.000000,object,---
162,internet_access:ssid,0,0.000000,object,---
186,contact:tiktok,0,0.000000,object,---
190,diet:raw,0,0.000000,object,---
182,check_date:diet:vegetarian,0,0.000000,object,---
158,diet:meat,0,0.000000,object,---
181,check_date:diet:vegan,0,0.000000,object,---
165,contact:threads,0,0.000000,object,---
179,disused:shop,0,0.000000,object,---
167,drink:beer,0,0.000000,object,---
177,diet:gluten_free,0,0.000000,object,---
176,addr:street:ru,0,0.000000,object,---
168,drink:coffee,0,0.000000,object,---
169,drink:tea,0,0.000000,object,---
159,check_date:smoking,0,0.000000,object,---
170,drink:cider,0,0.000000,object,---
171,drink:kombucha,0,0.000000,object,---
172,was:shop,0,0.000000,object,---
173,name:ja,0,0.000000,object,---
166,changing_table,0,0.000000,object,---
4,name:ru,0,0.000000,object,---
191,live_music,0,0.000000,object,---
223,height,0,0.000000,object,---
214,leisure,0,0.000000,object,---
215,rooms,0,0.000000,object,---
216,source:addr:housenumber,0,0.000000,object,---
217,power,0,0.000000,object,---
218,check_date:diet:halal,0,0.000000,object,---
219,building:colour,0,0.000000,object,---
221,building:condition,0,0.000000,object,---
222,building:max_level,0,0.000000,object,---
224,layer,0,0.000000,object,---
192,phone2,0,0.000000,object,---
225,building:facade:colour,0,0.000000,object,---
226,stars,0,0.000000,object,---
227,nohousenumber,0,0.000000,object,---
228,indoor,0,0.000000,object,---
229,building:levels:underground,0,0.000000,object,---
230,type,0,0.000000,object,---
231,was:amenity,0,0.000000,object,---
2,name,0,0.000000,object,---
213,contact:booking,0,0.000000,object,---
212,roof:levels,0,0.000000,object,---
211,old_name:ru,0,0.000000,object,---
156,cafe,0,0.000000,object,---
193,power_supply,0,0.000000,object,---
194,socket:schuko,0,0.000000,object,---
195,price,0,0.000000,object,---
196,name:zh,0,0.000000,object,---
197,historic,0,0.000000,object,---
198,wikipedia,0,0.000000,object,---
199,barrier,0,0.000000,object,---
201,diet:local,0,0.000000,object,---
202,roof:shape,0,0.000000,object,---
203,landuse,0,0.000000,object,---
204,building:part,0,0.000000,object,---
205,amenity_1,0,0.000000,object,---
206,building:form,0,0.000000,object,---
207,building:material,0,0.000000,object,---
208,landscape,0,0.000000,object,---
209,roof:material,0,0.000000,object,---
210,visual:condition,0,0.000000,object,---
157,contact:twitter,0,0.000000,object,---
119,name:fr,0,0.000000,object,---
155,toilets:unisex,0,0.000000,object,---
91,contact:phone,0,0.000000,object,---
76,cash_in,0,0.000000,object,---
77,payment:american_express,0,0.000000,object,---
84,start_date,0,0.000000,object,---
86,diet:non-vegetarian,0,0.000000,object,---
87,diet:organic,0,0.000000,object,---
89,name:signed,0,0.000000,object,---
90,sport,0,0.000000,object,---
92,value,0,0.000000,object,---
71,name_1,0,0.000000,object,---
93,contact:email,0,0.000000,object,---
94,payment:coins,0,0.000000,object,---
95,payment:cryptocurrencies,0,0.000000,object,---
96,payment:diners_club,0,0.000000,object,---
97,payment:electronic_purses,0,0.000000,object,---
98,payment:jcb,0,0.000000,object,---
100,payment:notes,0,0.000000,object,---
72,name:ar,0,0.000000,object,---
70,facebook,0,0.000000,object,---
154,check_date:dispensing,0,0.000000,object,---
54,alt_name,0,0.000000,object,---
14,name:hy,0,0.000000,object,---
23,tourism,0,0.000000,object,---
32,name:el,0,0.000000,object,---
35,information,0,0.000000,object,---
39,food,0,0.000000,object,---
48,highway,0,0.000000,object,---
49,internet_access:type,0,0.000000,object,---
56,contact:website,0,0.000000,object,---
69,phone_1,0,0.000000,object,---
57,diet:halal,0,0.000000,object,---
58,diet:vegan,0,0.000000,object,---
59,diet:vegetarian,0,0.000000,object,---
63,addr:housename,0,0.000000,object,---
64,int_name,0,0.000000,object,---
65,brand:wikipedia,0,0.000000,object,---
68,description:ru,0,0.000000,object,---
103,contact:tripadvisor,0,0.000000,object,---
105,drink:wine,0,0.000000,object,---
106,website:menu,0,0.000000,object,---
143,pub,0,0.000000,object,---
134,old_name:hy,0,0.000000,object,---
137,lunch,0,0.000000,object,---
138,ele,0,0.000000,object,---
139,contact:vk,0,0.000000,object,---
140,highchair,0,0.000000,object,---
141,name:it,0,0.000000,object,---
142,coffee,0,0.000000,object,---
144,payment:mir,0,0.000000,object,---
109,addr:province:ar,0,0.000000,object,---
145,name:es,0,0.000000,object,---
146,name:ko,0,0.000000,object,---
147,phone:delivery,0,0.000000,object,---
148,payment:discover_card,0,0.000000,object,---
151,contact:whatsapp,0,0.000000,object,---
152,vegetarian,0,0.000000,object,---
153,addr:place,0,0.000000,object,---
133,old_name:en,0,0.000000,object,---
132,wikidata,0,0.000000,object,---
131,contact:foursquare,0,0.000000,object,---
129,official_name,0,0.000000,object,---
110,addr:province:en,0,0.000000,object,---
112,attribution,0,0.000000,object,---
115,toilets:access,0,0.000000,object,---
116,old_name,0,0.000000,object,---
3,name:en,0,0.000000,object,---
118,name:simple,0,0.000000,object,---
120,name:fa,0,0.000000,object,---
121,name:de,0,0.000000,object,---
122,branch,0,0.000000,object,---
123,brewery,0,0.000000,object,---
124,dog,0,0.000000,object,---
125,pets_allowed,0,0.000000,object,---
126,microbrewery,0,0.000000,object,---
127,parking,0,0.000000,object,---
128,fax,0,0.000000,object,---
117,Մելնիցա,0,0.000000,object,---